application:
    build: .
    volumes:
        - .:/var/www/
        - ./docker/logs:/var/www/app/logs
    tty: true
db:
    image: mysql
    ports:
        - 27017:27017
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: symfony
        MYSQL_USER: root
        MYSQL_PASSWORD: root
php:
    build: docker/php-fpm
    volumes_from:
        - application
    links:
        - db
nginx:
    build: docker/nginx
    ports:
        - 80:80
    links:
        - php
    volumes_from:
        - application
    volumes:
        - ./docker/logs/nginx/:/var/log/nginx
elk:
    image: willdurand/elk
    ports:
        - 81:80
    volumes:
        - ./docker/elk/logstash:/etc/logstash
        - ./docker/elk/logstash/patterns:/opt/logstash/patterns
    volumes_from:
        - application
        - php
        - nginx
